/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

/// ApplicationParams : Stores the global information associated with an application.
#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationParams {
    /// \\[approv\\] approval program.
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "approval-program")]
    pub approval_program: Vec<u8>,
    /// \\[clearp\\] approval program.
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "clear-state-program")]
    pub clear_state_program: Vec<u8>,
    /// The address that created this application. This is the address where the parameters and global state for this application can be found.
    #[serde(rename = "creator")]
    pub creator: String,
    /// \\[epp\\] the amount of extra program pages available to this app.
    #[serde(rename = "extra-program-pages", skip_serializing_if = "Option::is_none")]
    pub extra_program_pages: Option<i32>,
    /// Represents a key-value store for use in an application.
    #[serde(rename = "global-state", skip_serializing_if = "Option::is_none")]
    pub global_state: Option<Vec<models::TealKeyValue>>,
    #[serde(rename = "global-state-schema", skip_serializing_if = "Option::is_none")]
    pub global_state_schema: Option<Box<models::ApplicationStateSchema>>,
    #[serde(rename = "local-state-schema", skip_serializing_if = "Option::is_none")]
    pub local_state_schema: Option<Box<models::ApplicationStateSchema>>,
}

impl ApplicationParams {
    /// Stores the global information associated with an application.
    pub fn new(approval_program: Vec<u8>, clear_state_program: Vec<u8>, creator: String) -> ApplicationParams {
        ApplicationParams {
            approval_program,
            clear_state_program,
            creator,
            extra_program_pages: None,
            global_state: None,
            global_state_schema: None,
            local_state_schema: None,
        }
    }
}

