/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApplicationInitialStates : An application's initial global/local/box states that were accessed during simulation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationInitialStates {
    #[serde(rename = "app-boxes", skip_serializing_if = "Option::is_none")]
    pub app_boxes: Option<Box<models::ApplicationKvStorage>>,
    #[serde(rename = "app-globals", skip_serializing_if = "Option::is_none")]
    pub app_globals: Option<Box<models::ApplicationKvStorage>>,
    /// An application's initial local states tied to different accounts.
    #[serde(rename = "app-locals", skip_serializing_if = "Option::is_none")]
    pub app_locals: Option<Vec<models::ApplicationKvStorage>>,
    /// Application index.
    #[serde(rename = "id")]
    pub id: i32,
}

impl ApplicationInitialStates {
    /// An application's initial global/local/box states that were accessed during simulation.
    pub fn new(id: i32) -> ApplicationInitialStates {
        ApplicationInitialStates {
            app_boxes: None,
            app_globals: None,
            app_locals: None,
            id,
        }
    }
}

