/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

/// ApplicationStateOperation : An operation against an application's global/local/box state.
#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationStateOperation {
    /// For local state changes, the address of the account associated with the local state.
    #[serde(rename = "account", skip_serializing_if = "Option::is_none")]
    pub account: Option<String>,
    /// Type of application state. Value `g` is **global state**, `l` is **local state**, `b` is **boxes**.
    #[serde(rename = "app-state-type")]
    pub app_state_type: String,
    /// The key (name) of the global/local/box state.
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "key")]
    pub key: Vec<u8>,
    #[serde(rename = "new-value", skip_serializing_if = "Option::is_none")]
    pub new_value: Option<Box<models::AvmValue>>,
    /// Operation type. Value `w` is **write**, `d` is **delete**.
    #[serde(rename = "operation")]
    pub operation: String,
}

impl ApplicationStateOperation {
    /// An operation against an application's global/local/box state.
    pub fn new(app_state_type: String, key: Vec<u8>, operation: String) -> ApplicationStateOperation {
        ApplicationStateOperation {
            account: None,
            app_state_type,
            key,
            new_value: None,
            operation,
        }
    }
}

