/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AssetHoldingReference : References an asset held by an account.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetHoldingReference {
    /// Address of the account holding the asset.
    #[serde(rename = "account")]
    pub account: String,
    /// Asset ID of the holding.
    #[serde(rename = "asset")]
    pub asset: i32,
}

impl AssetHoldingReference {
    /// References an asset held by an account.
    pub fn new(account: String, asset: i32) -> AssetHoldingReference {
        AssetHoldingReference {
            account,
            asset,
        }
    }
}

