/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Asset : Specifies both the unique identifier and the parameters for an asset
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Asset {
    /// unique asset identifier
    #[serde(rename = "index")]
    pub index: i32,
    #[serde(rename = "params")]
    pub params: Box<models::AssetParams>,
}

impl Asset {
    /// Specifies both the unique identifier and the parameters for an asset
    pub fn new(index: i32, params: models::AssetParams) -> Asset {
        Asset {
            index,
            params: Box::new(params),
        }
    }
}

