/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

/// BoxDescriptor : Box descriptor describes a Box.
#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BoxDescriptor {
    /// Base64 encoded box name
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "name")]
    pub name: Vec<u8>,
}

impl BoxDescriptor {
    /// Box descriptor describes a Box.
    pub fn new(name: Vec<u8>) -> BoxDescriptor {
        BoxDescriptor {
            name,
        }
    }
}

