/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTransactionGroupLedgerStateDeltasForRound200Response {
    #[serde(rename = "Deltas")]
    pub deltas: Vec<models::LedgerStateDeltaForTransactionGroup>,
}

impl GetTransactionGroupLedgerStateDeltasForRound200Response {
    pub fn new(deltas: Vec<models::LedgerStateDeltaForTransactionGroup>) -> GetTransactionGroupLedgerStateDeltasForRound200Response {
        GetTransactionGroupLedgerStateDeltasForRound200Response {
            deltas,
        }
    }
}

