/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

/// Box : Box name and its content.
#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Box {
    /// \\[name\\] box name, base64 encoded
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "name")]
    pub name: Vec<u8>,
    /// The round for which this information is relevant
    #[serde(rename = "round")]
    pub round: i32,
    /// \\[value\\] box value, base64 encoded.
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "value")]
    pub value: Vec<u8>,
}

impl Box {
    /// Box name and its content.
    pub fn new(name: Vec<u8>, round: i32, value: Vec<u8>) -> Box {
        Box {
            name,
            round,
            value,
        }
    }
}

