/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScratchChange : A write operation into a scratch slot.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScratchChange {
    #[serde(rename = "new-value")]
    pub new_value: Box<models::AvmValue>,
    /// The scratch slot written.
    #[serde(rename = "slot")]
    pub slot: i32,
}

impl ScratchChange {
    /// A write operation into a scratch slot.
    pub fn new(new_value: models::AvmValue, slot: i32) -> ScratchChange {
        ScratchChange {
            new_value: Box::new(new_value),
            slot,
        }
    }
}

