/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SimulateTraceConfig : An object that configures simulation execution trace.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SimulateTraceConfig {
    /// A boolean option for opting in execution trace features simulation endpoint.
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<bool>,
    /// A boolean option enabling returning scratch slot changes together with execution trace during simulation.
    #[serde(rename = "scratch-change", skip_serializing_if = "Option::is_none")]
    pub scratch_change: Option<bool>,
    /// A boolean option enabling returning stack changes together with execution trace during simulation.
    #[serde(rename = "stack-change", skip_serializing_if = "Option::is_none")]
    pub stack_change: Option<bool>,
    /// A boolean option enabling returning application state changes (global, local, and box changes) with the execution trace during simulation.
    #[serde(rename = "state-change", skip_serializing_if = "Option::is_none")]
    pub state_change: Option<bool>,
}

impl SimulateTraceConfig {
    /// An object that configures simulation execution trace.
    pub fn new() -> SimulateTraceConfig {
        SimulateTraceConfig {
            enable: None,
            scratch_change: None,
            stack_change: None,
            state_change: None,
        }
    }
}

