/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SimulateInitialStates : Initial states of resources that were accessed during simulation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SimulateInitialStates {
    /// The initial states of accessed application before simulation. The order of this array is arbitrary.
    #[serde(rename = "app-initial-states", skip_serializing_if = "Option::is_none")]
    pub app_initial_states: Option<Vec<models::ApplicationInitialStates>>,
}

impl SimulateInitialStates {
    /// Initial states of resources that were accessed during simulation.
    pub fn new() -> SimulateInitialStates {
        SimulateInitialStates {
            app_initial_states: None,
        }
    }
}

