/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SimulateUnnamedResourcesAccessed : These are resources that were accessed by this group that would normally have caused failure, but were allowed in simulation. Depending on where this object is in the response, the unnamed resources it contains may or may not qualify for group resource sharing. If this is a field in SimulateTransactionGroupResult, the resources do qualify, but if this is a field in SimulateTransactionResult, they do not qualify. In order to make this group valid for actual submission, resources that qualify for group sharing can be made available by any transaction of the group; otherwise, resources must be placed in the same transaction which accessed them.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SimulateUnnamedResourcesAccessed {
    /// The unnamed accounts that were referenced. The order of this array is arbitrary.
    #[serde(rename = "accounts", skip_serializing_if = "Option::is_none")]
    pub accounts: Option<Vec<String>>,
    /// The unnamed application local states that were referenced. The order of this array is arbitrary.
    #[serde(rename = "app-locals", skip_serializing_if = "Option::is_none")]
    pub app_locals: Option<Vec<models::ApplicationLocalReference>>,
    /// The unnamed applications that were referenced. The order of this array is arbitrary.
    #[serde(rename = "apps", skip_serializing_if = "Option::is_none")]
    pub apps: Option<Vec<i32>>,
    /// The unnamed asset holdings that were referenced. The order of this array is arbitrary.
    #[serde(rename = "asset-holdings", skip_serializing_if = "Option::is_none")]
    pub asset_holdings: Option<Vec<models::AssetHoldingReference>>,
    /// The unnamed assets that were referenced. The order of this array is arbitrary.
    #[serde(rename = "assets", skip_serializing_if = "Option::is_none")]
    pub assets: Option<Vec<i32>>,
    /// The unnamed boxes that were referenced. The order of this array is arbitrary.
    #[serde(rename = "boxes", skip_serializing_if = "Option::is_none")]
    pub boxes: Option<Vec<models::BoxReference>>,
    /// The number of extra box references used to increase the IO budget. This is in addition to the references defined in the input transaction group and any referenced to unnamed boxes.
    #[serde(rename = "extra-box-refs", skip_serializing_if = "Option::is_none")]
    pub extra_box_refs: Option<i32>,
}

impl SimulateUnnamedResourcesAccessed {
    /// These are resources that were accessed by this group that would normally have caused failure, but were allowed in simulation. Depending on where this object is in the response, the unnamed resources it contains may or may not qualify for group resource sharing. If this is a field in SimulateTransactionGroupResult, the resources do qualify, but if this is a field in SimulateTransactionResult, they do not qualify. In order to make this group valid for actual submission, resources that qualify for group sharing can be made available by any transaction of the group; otherwise, resources must be placed in the same transaction which accessed them.
    pub fn new() -> SimulateUnnamedResourcesAccessed {
        SimulateUnnamedResourcesAccessed {
            accounts: None,
            app_locals: None,
            apps: None,
            asset_holdings: None,
            assets: None,
            boxes: None,
            extra_box_refs: None,
        }
    }
}

