/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

/// Version : algod version information.
#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Version {
    #[serde(rename = "build")]
    pub build: Box<models::BuildVersion>,
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "genesis_hash_b64")]
    pub genesis_hash_b64: Vec<u8>,
    #[serde(rename = "genesis_id")]
    pub genesis_id: String,
    #[serde(rename = "versions")]
    pub versions: Vec<String>,
}

impl Version {
    /// algod version information.
    pub fn new(build: models::BuildVersion, genesis_hash_b64: Vec<u8>, genesis_id: String, versions: Vec<String>) -> Version {
        Version {
            build: Box::new(build),
            genesis_hash_b64,
            genesis_id,
            versions,
        }
    }
}

